services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    # depends_on:
    #   - db
    command: >
      bash -c "alembic upgrade head && 
              uvicorn app.main:app --host 0.0.0.0 --port 3000 --reload"

  # db:
  #   image: gvenzl/oracle-free:latest
  #   env_file:
  #     - .env
  #   ports:
  #     - "1521:1521"
  #   environment:
  #     - ORACLE_PASSWORD=${ORACLE_PASSWORD}
  #     - APP_USER=${APP_USER}
  #     - APP_USER_PASSWORD=${APP_USER_PASSWORD}

    # volumes:
    #   - ./oracle_data:/opt/oracle/oradata

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    # depends_on:
    #   - db 