"""table updated

Revision ID: 2b4a1e2b4ec5
Revises: 
Create Date: 2025-04-26 14:19:55.638365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4a1e2b4ec5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('last_login', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('wildlife',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=254), nullable=False),
    sa.Column('conservation_name_english', sa.String(length=254), nullable=False),
    sa.Column('conservation_area', sa.String(length=254), nullable=False),
    sa.Column('conservation_status', sa.String(length=254), nullable=False),
    sa.Column('count', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=254), nullable=False),
    sa.Column('united', sa.String(length=254), nullable=False),
    sa.Column('site', sa.String(length=254), nullable=False),
    sa.Column('mountain', sa.String(length=254), nullable=False),
    sa.Column('wadi', sa.String(length=254), nullable=False),
    sa.Column('ranger', sa.String(length=254), nullable=False),
    sa.Column('contact_person', sa.String(length=254), nullable=False),
    sa.Column('telephone_number', sa.Float(), nullable=False),
    sa.Column('east', sa.Float(), nullable=False),
    sa.Column('north', sa.Float(), nullable=False),
    sa.Column('date_entry', sa.Date(), nullable=False),
    sa.Column('time_entry', sa.String(length=254), nullable=False),
    sa.Column('remark', sa.String(length=254), nullable=False),
    sa.Column('created_user', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('last_edited_user', sa.String(length=255), nullable=False),
    sa.Column('last_edited_date', sa.Date(), nullable=False),
    sa.Column('animal_name_arabic', sa.Integer(), nullable=False),
    sa.Column('governorates', sa.Integer(), nullable=False),
    sa.Column('pasture', sa.Integer(), nullable=False),
    sa.Column('time_zone', sa.Integer(), nullable=False),
    sa.Column('person_entry', sa.Integer(), nullable=False),
    sa.Column('years', sa.Integer(), nullable=False),
    sa.Column('type_of_view', sa.Integer(), nullable=False),
    sa.Column('animal_name_english', sa.Integer(), nullable=False),
    sa.Column('wilaya', sa.Integer(), nullable=False),
    sa.Column('male', sa.Float(), nullable=False),
    sa.Column('female', sa.Float(), nullable=False),
    sa.Column('young', sa.Float(), nullable=False),
    sa.Column('attachment_1', sa.String(length=255), nullable=False),
    sa.Column('attachment_2', sa.String(length=255), nullable=False),
    sa.Column('attachment_3', sa.String(length=255), nullable=False),
    sa.Column('attachment_4', sa.String(length=255), nullable=False),
    sa.Column('attachment_5', sa.String(length=255), nullable=False),
    sa.Column('create_by', sa.String(length=50), nullable=False),
    sa.Column('change_by', sa.String(length=50), nullable=False),
    sa.Column('create_dat', sa.Date(), nullable=False),
    sa.Column('change_dat', sa.Date(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.String(length=50), nullable=False),
    sa.Column('gid', sa.String(length=500), nullable=False),
    sa.Column('wilaya_new', sa.Integer(), nullable=False),
    sa.Column('years_new', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wildlife_id'), 'wildlife', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wildlife_id'), table_name='wildlife')
    op.drop_table('wildlife')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ### 