"""table updated

Revision ID: 5141a9d237c7
Revises: 2b4a1e2b4ec5
Create Date: 2025-04-26 14:22:03.156319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5141a9d237c7'
down_revision = '2b4a1e2b4ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 