"""table updated

Revision ID: bd154bb1b29d
Revises: 5141a9d237c7
Create Date: 2025-04-26 14:23:29.090313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd154bb1b29d'
down_revision = '5141a9d237c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wildlife', 'client_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('wildlife', 'gid',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wildlife', 'gid',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('wildlife', 'client_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ### 